blank_issues_enabled: false
contact_links:
  - name: JsonMapper Community Support
    url: https://github.com/JsonMapper/JsonMapper/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://github.com/DannyvdSluijs/well-known-files/security/advisories/new
    about: Please report security vulnerabilities here.